language: node_js
node_js:
  - "6"
before_deploy:
  - npm run build
  - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
deploy:
  provider: script
  script: npm run publish
  skip_cleanup: true
  on:
    branch: master
    tags: true
notifications:
  email:
    on_success: never
    on_failure: never
