language: node_js
node_js:
  - "6"
before_deploy:
  - npm run build
deploy:
  provider: script
  script: ./scripts/publish.sh
  skip_cleanup: true
  on:
    branch: master
    # tags: true
    # node: "4"
