language: node_js
node_js:
- "6"
notifications:
  email:
    on_success: never
    on_failure: never
before_deploy:	
- npm run lint	
- npm run build
- echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc	
deploy:	
  provider: script	
  script: npm publish ./.build
    on:
    tags: true
    branch: master
